/* Don't modify this file. It has been autogenerated with the generate_clips.py script */
#include "types.h"

void clip_prince_init(figure_t *f);
void clip_prince_get_index(chr_state_t s, const uint16_t **ind);

